title: Socketing Reactoring Dev Log
description: Socketing 프로젝트 리팩토링 과정을 기록합니다.
baseurl: ''
url: 'https://socketing-refactoring.github.io'

google_analytics:

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category_archives
    tag: tag_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

collections:
  posts:
    output: true
  articles:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
