title: Socketing Reactoring Dev Log
description: Socketing 프로젝트 리팩토링 과정을 기록합니다.
baseurl: ""
url: "https://socketing-refactoring.github.io"

plugins:
  - jekyll-tagging
  - jekyll-archives

tag_page_layout: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

collections:
  posts:
    output: true
  articles:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
